export default {
    hero_small: require('./img/hero-small.jpg'),
    hero: require('./img/hero.jpg'),
    logo_green_1: require('./img/logo-green-1x.png'),
    logo_green_2: require('./img/logo-green-2x.png'),
    logo_green_small_1: require('./img/logo-green-small-1x.png'),
    logo_green_small_2: require('./img/logo-green-small-2x.png'),
    logo_white: require('./img/logo-white.png'),
    nat_1: require('./img/nat-1.jpg'),
    nat_1_large: require('./img/nat-1-large.jpg'),
    nat_2: require('./img/nat-2.jpg'),
    nat_2_large: require('./img/nat-2-large.jpg'),
    nat_3: require('./img/nat-3.jpg'),
    nat_3_large: require('./img/nat-3-large.jpg'),
    nat_4: require('./img/nat-4.jpg'),
    nat_5: require('./img/nat-5.jpg'),
    nat_6: require('./img/nat-6.jpg'),
    nat_7: require('./img/nat-7.jpg'),
    nat_8: require('./img/nat-8.jpg'),
    nat_9: require('./img/nat-9.jpg'),
    nat_10: require('./img/nat-10.jpg'),
};
